export const FILMS = [
  {
    id: 1,
    year: "2021",
    title: "La batalla olvidada",
    isViewed: true,
    comment: "good movie",
  },
  {
    id: 2,
    year: "2021",
    title: "El viaje",
    isViewed: true,
    comment: "good movie",
  },
  {
    id: 3,
    year: "2021",
    title: "Distancia de rescate",
    isViewed: true,
    comment: "good movie",
  },
  {
    id: 4,
    year: "2021",
    title: "Mi hermano, mi hermana",
    isViewed: true,
    comment: "good movie",
  },
  {
    id: 5,
    year: "2021",
    title: "Hay alguien en tu casa",
    isViewed: true,
    comment: "good movie",
  },
  {
    id: 6,
    year: "2021",
    title: "Nadie saldrá vivo de aquí",
    isViewed: true,
    comment: "good movie",
  },
  {
    id: 7,
    year: "1999",
    title: "Matrix",
    isViewed: true,
    comment: "good movie",
  },
  {
    id: 8,
    year: "2003",
    title: "Big fish",
    isViewed: true,
    comment: "good movie",
  },
  {
    id: 9,
    year: "2013",
    title: "La grande bellezza",
    isViewed: true,
    comment: "good movie",
  },
  {
    id: 10,
    year: "1993",
    title: "Jurassic park",
    isViewed: true,
    comment: "good movie",
  },
  {
    id: 11,
    year: "1994",
    title: "The Shawshank Redemption",
    isViewed: true,
    comment: "good movie",
  },
  {
    id: 12,
    year: "1997",
    title: "Good Will Hunting",
    isViewed: true,
    comment: "good movie",
  },
];
